### ISSUE TITLE
MessageContext.ToContextX12() can't find ST tag for Form 834

### ISSUE THREAD

**Issue by henrynguyen7** [DonZoeggerle/ediFabric#1]
When attempting to call `Interchange.ToEdi()` for a Message instance of HIPAA Form 834 version 005010, the EdiFabric Framework project fails on line 235 of `Framework/Messages/MessageContext.cs`. Specifically, when attempting to retrieve `XElement` in the following assignment,

```
var tag = st.Element(ns + EdiElements.StTag) ?? st.Element(ns + EdiElements.StTagHipaa);
```

`EdiElements.StTagHipaa` is "D_ST01" but the public field as defined in `Definitions/005010_834.cs` is "D_ST01_TransactionSetIdentifierCode", causing null to be assigned to `tag`. Hard-coding 

```
var tag = st.Element(ns + EdiElements.StTag + "_TransactionSetIdentifierCode");
```

fixes this issue so the incorrect name is verified to be the problem. 

I've modified the code to search for any `XElements` in which the name simply begins with either `EdiElements.StTag` or `EdiElements.StTagHipaa`. Pull request incoming.

**Comment by doveraudio** [comment]
I can confirm this fix in 837p as well. I was having the same issue, and this fixed it. Thanks.

**Comment by DonZoeggerle** [comment]
This was merged into master. Closing the issue.
