### ISSUE TITLE
EdiStream hangs

### ISSUE THREAD

**Issue by elvogel** [DonZoeggerle/ediFabric#15]
I am attempting to use the EdiStream object on a ~6MB file, and it seems to be hanging. I'm not sure if it's because I'm using the wrong schema for my message, but it appears to be parsing the entire file. I have a log file that seems to indicate that it is parsing the whole thing. It's filled with the text below.

Thanks

Segment to find: Name = ST Value = 834 ParentId = 
Segment to try: S_ST
Segment found: S_ST
Segment to find: Name = BGN Value = 00 ParentId = 
Segment to try: S_ST
Segment to try: S_BGN
Segment found: S_BGN
Segment to find: Name = DTP Value = 007 ParentId = 
Segment to try: S_BGN
Segment to try: S_REF
Segment to try: S_DTP
Segment found: S_DTP
Segment to find: Name = N1 Value = P5 ParentId = 
Segment to try: S_DTP
Segment to try: S_AMT
Segment to try: S_QTY
Segment to try: G_N1
Segment found: S_N1
Segment to find: Name = N1 Value = IN ParentId = 
Segment to try: S_N1
Segment found: S_N1
Segment to find: Name = INS Value = Y ParentId = 
Segment to try: S_N1
Segment to try: S_N2
Segment to try: S_N3
Segment to try: S_N4
Segment to try: S_PER
Segment to try: G_ACT
Segment to try: G_N1
Segment to try: G_INS
Segment found: S_INS
Segment to find: Name = REF Value = 0F ParentId = 
Segment to try: S_INS
Segment to try: S_REF_3
Segment found: S_REF_3
Segment to find: Name = REF Value = 1L ParentId =

**Comment by DonZoeggerle** [comment]
`Have you added references to Definitions project in your app.config, e.g.:
<add key="EdiFabric.Definitions" value="EdiFabric.Definitions" />
<add key="EdiFabric.Validators" value="EdiFabric.Validators" />`

**Comment by DonZoeggerle** [comment]
On the other note - EdiStream doesn't load the whole file in memory, but instead parses it message by message. For example while a 1 MB EDI file is parsed the memory:
1. Using Interchange, the memory footprint builds up gradually up to 20MB.
2. Using EdiStream, the memory footprint is flat 7MB.

**Comment by DonZoeggerle** [comment]
I'd appreciate if you could share the message and will try to run it my end otherwise will close the issue.
