### ISSUE TITLE
GetAssemblyName() fails to retrieve the Definitions assembly

### ISSUE THREAD

**Issue by mplogix** [DonZoeggerle/ediFabric#16]
InterchangeContext.GetAssemblyName() fails to retrieve the Definitions assembly when the client is not a Console assembly.
If the client of the Framework is a simple class library (I am using a NUnit test project) GetAssemblyName does not return the default Edifabric.Definitions assembly, as the call to ConfigurationManager.AppSettings["EdiFabric.Definitions"] returns 'null' without raising an exception. A simple 'if' statement in the try block that returns "EdiFabric.Definitions", when the call to ConfigurationManager returns null, can fix that.

**Comment by DonZoeggerle** [comment]
Yes you are correct - I will include this in the next release.
