### ISSUE TITLE
Issue with streaming of files

### ISSUE THREAD

**Issue by TheArPee** [DonZoeggerle/ediFabric#18]
I have been trying out the new EDIStream enhancements and have come across a problem. Many files the we receive at work are from different sources. Some of them use the windows line terminators (CRLF) and some use the Unix/Apple line terminators (LF).
The code in the ReadSegment function in the EDIHelper.cs:
  "line = line.Replace(Environment.NewLine, string.Empty);"
will - in a file with Unix line terminators running on a windows PC - NOT remove the LFs and corrupt the reading of the second and subsequent segments as they will all start with the LF character.
An inelegant solution we use (as we sometimes get files with mixed line terminators) is to convert all CRLF's to LF and then convert all LF's to String.Empty.
I am sure that there are many ways to deal with this and I am sure that you will find a much more elegant way. :-)

**Comment by DonZoeggerle** [comment]
This is correct, I will include this in the next release.

**Comment by TheArPee** [comment]
Like your way much better than ours! :-)
