### ISSUE TITLE
Expects wrong namespace for custom-generated classes

### ISSUE THREAD

**Issue by zaus** [DonZoeggerle/ediFabric#20]
I downloaded the [002040 X12 samples](http://edifabric.com/edifabricweb/00204.zip) from http://edifabric.com/x12/ and generated the classes. _(aside: why not just provide the `.cs` files directly?)_

It created the classes under namespace `EdiFabric.Definitions.X12_002040_850` (note the **002040** matching the download set name).

Following the guide instructions on http://edifabric.com/guide/, I added those files directly to my solution in a new project "Definitions".
In another project using the `ediFabric` NuGet package I basically copied the `Load` helper from the SDK project https://github.com/DonZoeggerle/ediFabric.Sdk.EdiToObject, the relevant line being:

	// Parse the EDI
	// Pass in the name of the assembly because the class is not in the default assembly (configured in app.config or EdiFabric.Definitions)
	interchange = Interchange.LoadFrom(source, "Definitions");
	... later
	yield return msg.DeserializeItem<T>(); // where T is supposed to be one of the autogenerated message classes

A unit test in another project of the same solution, referencing both projects, failed with the following exception:

> Test method Edi.Tests.EdiConversionTests.Edi_Load threw exception: 
System.Exception: Failed to load edi source stream ---> EdiFabric.Framework.ParserException: Can't find type for type name = EdiFabric.Definitions.X12_004010_850.M_850, Definitions

I was wracking my brains trying figure out why it couldn't find the type (had I not named the assemblies correctly?  included them properly) when I noticed the namespace it's looking for (note the **004010** which is from another download set?) didn't match the class I had included and referenced.

After going in to the autogenerated class and replacing `002040` with `004010` it loads correctly.

**Comment by zaus** [comment]
It might also help to offer a generic-type overload that automatically gets the definition assembly name from the provided type, like:

	public Interchange LoadFrom<T>(Stream source) {
		var type = typeof(T);
		// would have liked to just pass `type.AssemblyQualifiedName`

		var actualAssembly = type.GetAssembly().Name;
		var fabricExpectedAssemblyName = actualAssembly.Substring(0, actualAssembly.IndexOf(", Version"));
		return Interchange.LoadFrom(source, fabricExpectedAssemblyName);
	}

**Comment by DonZoeggerle** [comment]
Hi,

The error you are getting:

Test method Edi.Tests.EdiConversionTests.Edi_Load threw exception: 
System.Exception: Failed to load edi source stream ---> EdiFabric.Framework.ParserException: Can't find type for type name = EdiFabric.Definitions.X12_004010_850.M_850, Definitions

means that you don't have the the 004010 class added to your definitions project.
Changing the namespace is not recommended as what this effectively means is that you will try to parse a 004010 edi with 002040 definition, which will fail in 90% of the situations and can't be relied upon.

You can set the assembly name in 3 ways:
1. Not set it all (you need to name your definition project EdiFabric.Definitions then).
2. Set the project name in the app\web config.
3. Pass it as a parameter (read the getting started page):
var interchange = Interchange.LoadFrom(File.OpenRead(@"c:\test.edi"), "MyAssembly.MyProject");

**Comment by zaus** [comment]
After re-reading your reply several times it suddenly clicked -- the EDI parser _knows what definition version it's supposed to load_, which is why it keeps looking for 004010 rather than 002040.  What I didn't realize (and am still not totally clear on) is that {{M_850}} from the 002040 group is different than the 004010 group.  Thank you for pointing out the difference.

Is there a way to tell from the EDI which definition version I should use?  For the 850 document, I think it's:

> ISA12 I11 Interchange Control Version Number

(specifically, with Amazon Vendor Central integration)

**Comment by DonZoeggerle** [comment]
The EDI parser picks up the definition it needs to load from the EDI message. There is the EDI envelope and some other important segments that identify the EDI transaction and version. The parser then goes and checks if a class supporting that transaction and version exist and if it does - loads it and carries on with parsing the message. If not - then it throws the above exception.
The segments you mentioned do define the message type and version - you just need to ensure the correct class is present in the Definitions project.
