### ISSUE TITLE
Error in 2000C loop with 6.6

### ISSUE THREAD

**Issue by sbanner** [DonZoeggerle/ediFabric#22]
We have 4010 and 5010 test files we run after every upgrade and all have been successful on past versions.  With 6.6 we are getting an "Object reference not set to an instance of an object" error when processing 5010 test files with the 2000C loop.  We isolated it to the FindNextSegment method in the ParseTree class.  For the 837I, the parent shows correctly as "G_TS837_2000C", the child count is correct at 4 and the child indexes and names are correct as 0 = S_HL_PatientHierarchicalLevel, 1 = S_PAT_PatientInformation, 2 = G_TS837_2010CA and 3 = G_TS837_2300_1.  The problem occurs in the foreach loop.  All the properties are false except IsSegment, which causes it to not return anything from the foreach loop.  For example, segment "PAT*19" should hit the "return child" of the first "if" in the foreach loop, but it doesn't.

        public ParseTree FindNextSegment(SegmentContext segmentContext)
        {
            // Look on the same level first
            foreach (var child in Parent.Children.Skip(GetIndex()))
            {
                Logger.Log(string.Format("Segment to try: {0}", child.Name));
                
                if (child.IsSegment && child.IsEqual(segmentContext))
                    return child;

                if (child.IsGroup && child.Children.First().IsEqual(segmentContext))
                    return child.Children.First();

                // Search a level down
                if (child.IsAll || child.IsChoice || child.IsLoopOfLoops)
                    return child.Children.First().FindNextSegment(segmentContext);
            }

            // Search a level up
            return Parent.FindNextSegment(segmentContext);
        }

**Comment by DonZoeggerle** [comment]
The latest change in version 6.6 is that HIPAA segmenta are identified by segment name as well as the value of the first element AND the value of the second element if they are enums. In your case it'll be
PAT*19*??? should match the definition for that second element. Could you please post the next element in the PAT segment and which transaction are you trying to parse ? 
Cheers, Kamen

**Comment by sbanner** [comment]
The transactions trying to be parsed are HIPAA 5010 837 Professional and Institutional.  For the institutional the only element used in the PAT segment is the first, so looking for the second isn't valid.  For the professional, the 2nd, 3rd and 4th elements aren't used, so looking for the second also isn't valid.
837I - PAT*19 (That is all there will be)
837P - PAT*19****D8*20150521*01*156*

Was this change to look at the second element only made for parsing a 5010?  We have 4010 test files set up the same as the 5010 that work just fine.

**Comment by kjsdad** [comment]
Why is this closed?

**Comment by sbanner** [comment]
Accidentally closed.  Please look into.

**Comment by DonZoeggerle** [comment]
Could you please enable logging and send me the output for the PAT segment?
To enable logging add this to the web\app.config:
<add key="EdiFabric.LogFile" value="C:\log.txt" />
I did test this and is working as expected:

var pt = new ParseTree
            {
                Name = "S_PAT",
                FirstElementValues = new List<string> {"19", "18"},
                SecondElementValues = new List<string> {"A", "B"}
            };
            
            var sc = new SegmentContext("PAT*19***", new InterchangeContext
            {
                DataElementSeparator = "*",
                
            }, EdiFormats.X12);


            var e = pt.IsEqual(sc);

            // e is TRUE

**Comment by sbanner** [comment]
Here is what was output

 

Scott Banner 

BI & Solution Architect

International Outsourcing, Inc.
scott <mailto:kevin@ioutsource.com> @ioutsource.com

Cell: 208-870-7739

**Comment by DonZoeggerle** [comment]
This was fixed in release 6.7.0 - please confirm.
