### ISSUE TITLE
Embedded "??" in FTX is not properly un-escaped when being read in. 

### ISSUE THREAD

**Issue by clafollett** [DonZoeggerle/ediFabric#23]
While attempting to read in a DESADV EDI message from our fulfillment partner, we found embedded escaped question marks ("??") were not being un-escaped. The FTX segment in the DESADV message below contains a URL which has query parameters. The "??" is not properly being unescaped to a single "?":

```
UNB+UNOC:3+CLEARINGCENTER+CLIENT+160303:1520+27'
UNH+14+DESADV:D:99B:UN'
BGM+351:::Despatch advise+111111+9'
DTM+137:20160303:102'
DTM+11:20160303:102'
TOD+6'
FTX+DEL+++http?://someurl.com/trace/tracking.cgi??refnr=111111'
TDT+30'
CPS+00001+DUMMY+4'
PAC+1+4+NPA'
LIN+1++47880124521:SA'
PIA+4+788 012 452:SA'
QTY+12:1:EA'
QTY+21:1:EA'
RFF+ON:123456789:00001'
DTM+137:20160303:102'
UNT+19+14'
UNZ+1+27'
```

I pulled your ediFabric source from git and modified your Edifact_INVOIC_D00A_EscaptedEscape TXT and XML files as follows:

![image](https://cloud.githubusercontent.com/assets/5647494/13756640/33b4a0ea-e9f7-11e5-8296-2617d1b48c73.png)

Doing so causes the TestToInterchangeWithEscapedEscape Unit Test to fail:

![image](https://cloud.githubusercontent.com/assets/5647494/13756685/6538ef0e-e9f7-11e5-9f11-e540e1b02de9.png)

It appears the escaped "?" is only un-escaped if the escaped escape is at the end of a segment's value as seen with the "AAI??" in the FTX -> 4451 segment.

I've not debugged your source but in looking, this issue appears to be due to line 229 of the EdiHelper.EscapeSplit method:

![image](https://cloud.githubusercontent.com/assets/5647494/13756794/fd88411a-e9f7-11e5-8dfe-3e16da1c497f.png)

**Comment by DonZoeggerle** [comment]
Thank you for raising this, it's been fixed in release 6.7.1
