### ISSUE TITLE
Cant't Parse 997 FA File containing TA1 Segment

### ISSUE THREAD

**Issue by praveencbe0** [DonZoeggerle/ediFabric#26]
Hi,

The Library is great. Recently I have received an 997 Functional Acknowledgement file which contains a new segment known as TA1 and the edi parser is not able to parse the 997 file.

[FA-997.txt](https://github.com/DonZoeggerle/ediFabric/files/239075/FA-997.txt)

This is an valid 997 Edi file. I checked the Interchange class it does not have any TA1 segment.

**Related webpages:**
https://msdn.microsoft.com/en-us/library/cc982721(v=bts.10).aspx
https://msdn.microsoft.com/en-us/library/cc973722(v=bts.10).aspx

Is there anyway we can parse this file using edi parser. Thanks for helping out.

cheers.

**Comment by DonZoeggerle** [comment]
Hi,
We currently don't support TA1 segment in 997 acknowledgements. It should be relatively easy to handcraft it using the [rules](http://edifabric.com/edifabricweb/EdiClassGuide.pdf).

**Comment by DonZoeggerle** [comment]
I'll add this to the pipeline for the next release.

**Comment by DonZoeggerle** [comment]
This will not go into the next release, but later on. I will close the issue as it's a feature request, which we have acknowledged.
Regards,
Don
