### ISSUE TITLE
Issue parsing HLH in 834

### ISSUE THREAD

**Issue by ghost** [DonZoeggerle/ediFabric#27]
Exception while parsing HLH*N~ in 834. Segment parser checks for segment starting with HL and applies HL splitting for HLH erroneously. Below addresses issue.

SegmentContext.cs line 78 should be

if (ediSegment.StartsWith(EdiSegments.Hl) **&& !ediSegment.StartsWith("HLH") **&& !string.IsNullOrEmpty(splitted[2])) ParentId = splitted[2];

instead of

if (ediSegment.StartsWith(EdiSegments.Hl) && !string.IsNullOrEmpty(splitted[2])) ParentId = splitted[2];

Thanks

**Comment by DonZoeggerle** [comment]
Fixed in version 6.7.2
