### ISSUE TITLE
HIPAA Looping

### ISSUE THREAD

**Issue by GraysonStuntz** [DonZoeggerle/ediFabric#30]
It looks like there is a recursion issue with the ParseTree.FindNextSegment. I am trying to parse a HIPAA 834. In the parse tree when looking for the INS(Member Detail), it first searches the  G_TS834_1000B, doesnt find anything(correctly) and then start searching the A_N1. It doesnt find anything in the first two regular groups, but then it hits U_TS834_1000C and calls child.Children.First().FindNextSegment(segmentContext). It doesnt find the segment there, but instead of returning nothing, it calls Parent.FindNextSegment(segmentContext). At this point the Parent is the A_N1, so it gets caught in an infinite loop. I cannot think of an easy way to prevent the infinite loop, and will likely try a few things to see if I can get it to work.
Thanks,
Grayson

**Comment by GraysonStuntz** [comment]
I ended up being able to correct the recursion issue by changing the method to as follows, I did not do extensive testing, but I think that it should work generically.
 public ParseTree FindNextSegment(SegmentContext segmentContext, bool isChildLoops = false)
        {
            if (Parent == null)
                throw new ParserException(string.Format("Can't find a match for segment {0}. Message is invalid.",
                    segmentContext.ToPropertiesString()));

            // Look on the same level first
            foreach (var child in Parent.Children.Skip(GetIndex()))
            {
                Logger.Log(string.Format("Segment to try: {0}", child.Name));
                
                if (child.IsSegment && child.IsEqual(segmentContext))
                    return child;

                if (child.IsGroup && child.Children.First().IsEqual(segmentContext))
                    return child.Children.First();

                // Search a level down
                if (child.IsAll || child.IsChoice || child.IsLoopOfLoops)
                {
                    var ret = child.Children.First().FindNextSegment(segmentContext, true);
                    if(ret != null)
                    {
                        return ret;
                    }
                }
                     
            }

            if (isChildLoops)
            {
                return null;
            }

            // Search a level up
            return Parent.FindNextSegment(segmentContext);
        }

**Comment by DonZoeggerle** [comment]
Hi,
There is a new version of HIPAA 834 - please request it on office@edifabric.com - there are no U_ elements anymore.
Regards,
Don

**Comment by DonZoeggerle** [comment]
U_ elements are back in with the next release (sometime net week), but the issue will be resolved.

**Comment by DonZoeggerle** [comment]
Closing the issue - resolved in version 6.7.5
