### ISSUE TITLE
The validator uses the escapted length of a string

### ISSUE THREAD

**Issue by luckolen** [DonZoeggerle/ediFabric#31]
The S_N3.D_166_1 in a 855 has a max length of 55 characters. But a string that is 54 characters with one of the characters being a ' will result in an error. A ' becomes a &apos; and that turns the original 54 characters into 59 characters. 
This shouldn't result in an error because the original string of 54 characters was valid.

The segment that results in an error:
> N3^XXXX  XXXXX XXXXX XXXXXXXX'X XXXXXXXX XXXXXXXXXX XXXXX^XXXXX XXXXX XXXXXXXX'X XXXXXX~

**Comment by DonZoeggerle** [comment]
This will be resolved in the next release, which has all of the Xml bits taken out.

**Comment by DonZoeggerle** [comment]
Closing the issue - resolved in version 6.7.5
