### ISSUE TITLE
Parsing Optimization

### ISSUE THREAD

**Issue by tmeindle** [DonZoeggerle/ediFabric#35]
Hello,

Consider changing all calls to string.StartsWith(someString) to string.StartsWith(someString, StringComparison.Ordinal) and changing string.EndsWith(someString) to string.EndsWith(someString, StringComparison.Ordinal).

Starts(Ends)With(someString) performs a culture and case sensitive compare which should not be needed for parsing segment tags and separators.  

I get anywhere from a 33% to 45% increase in parsing speed using ordinal compare.

"Use StringComparison.Ordinal or StringComparison.OrdinalIgnoreCase for comparisons as your safe default for culture-agnostic string matching.

Use comparisons with StringComparison.Ordinal or StringComparison.OrdinalIgnoreCase for better performance."
[Best Practices for Using Strings in the .NET Framework](https://msdn.microsoft.com/en-us/library/dd465121.aspx)

-Tim M.

**Comment by DonZoeggerle** [comment]
Updated to use StringComparison.OrdinalIgnoreCase for all StartsWith & EndsWith
