### ISSUE TITLE
Observation

### ISSUE THREAD

**Issue by tmeindle** [DonZoeggerle/ediFabric#36]
Hello..  

I recently upgraded from 4.1 (pre-hipaa) to 6.x and just thought I would share my observations so far while trying to migrate my old application code to use the new library / schemas.

The new hipaa 5010 xsds make it infinitely easier to validate any 837 message for any given hipaa version..  

However it dramatically increases the amount of code I needed to actually parse an 837 message..  With version 4.1 I used the single 5010 837 Superset XSD/Class hierarchy to "manually" validate depending on the x12 version (005010X222, 005010X222A1, 005010X223A1, 005010X223A2, 005010X224A1,  005010X224A2).

For parsing I would load the message into memory and then iterate through the HLs splitting out the a single table as needed (one provider, subscriber, and patient).  If the a PatientHL is not present then PatientHL = SubscriberHL.    

```
public class M_837_Table
{
    public ClaimType ClaimType; //(Institutional, Professional, Dental) based on the x12 version
    public G_HL ProviderHL;
    public G_HL SubscriberHL;
    public G_HL PatientHL;
}

```
In this way a single function taking an M_837_Table as it parameter could be crafted to parse Institutional, Professional, or Dental claims. Much of the spec is the same between the the different versions.  For example the Billing Provider name loop always starts with a NM1 segment where NM1.01 = 85. 

```
IList<FlatClaimLineRecord> Transform837(M_837_Table table)
{
     var records = new List<FlatClaimRecord>();
	 //Grab billing provider info from table.ProviderHL
     //Grab Subscriber info from table.SubscriberHL
     //Grab Patient info from table.PatientHL which could be the same as the subscriber

    //Grab each claim and make a flat record using the ClaimType to grab specific information
    foreach (G_CLM clmSeg in PatientHL)
    {
        //Parse everything that is common between specs (Diagnoses, Claim number, etc)
         
		//Then parse stuff out that is specific to each claim type
		switch(ClaimType)
        {
			case ClaimType.Instutional:
				break;
			case ClaimType.Professional:
				break;
			case ClaimType.Dental:
				break;
		}
		 
		foreach (var claimLineLX in claimCLM.G_LX)
        {
			var record = new FlatClaimLineRecord();
			//Parse everything that is common on lines between specs (Line Id, Service dates, charge amounts etc)
         
			//Then parse stuff out that is specific to each claim type line
			switch(ClaimType)
			{
				case ClaimType.Instutional:
					break;
				case ClaimType.Professional:
					break;
				case ClaimType.Dental:
					break;
			}
			records.Add(record);
		}
    }
	return records;
}

```

With the new Hipaa specific xsd/classes I have to craft a function for each spec version as there is no common base.  Furthermore the structure is much more rigid.  I can't set Patient = Subscriber and both have their own type definitions for the 2300 claim loop and the 2400 loops even though it is exactly the same logic.

```
IList<FlatClaimLineRecord> Transform005010X223A2(EdiFabric.Rules.X12005010X223A2837.G_TS837_2000A table )
{
	var records = List<FlatClaimLineRecord>();
	//Grab billing provider info from table.ProviderHL
	foreach (var subscriber in table.G_TS837_2000B)
	{
		//if there are patient segments we grab claims from that since 
		//the subscriber should not have any claims associated with it.
		if (subscriber.G_TS837_2000C != null)  
		{
			foreach(var patient in subscriber.G_TS837_2000C)
			{
				//parse out demographic information
				foreach (var claim in patient.G_TS837_2300_1)
				{
					//parse out claim information
					foreach (var line in claim.G_TS837_2400_1)
					{
						//Parse out line information
         				records.Add(record);
					}
				}
			}
		}
		else
		{
			//parse out demographic information.. Same exact logic as above but a different type
			foreach (var claim in subscriber.G_TS837_2300)
			{
				//parse out claim information.. Same exact logic as above but a different type
				foreach (var line in claim.G_TS837_2400)
				{
					//Parse out line information.. Same exact logic as but a different type
					records.Add(record);
				}
			}
		}
	}
	return records;
}

IList<FlatClaimLineRecord> Transform005010X222A1(EdiFabric.Rules.X12005010X223A2837.G_TS837_2000A table )
{
	var records = List<FlatClaimLineRecord>();
	//Grab billing provider info from table.ProviderHL
	foreach (var subscriber in table.G_TS837_2000B)
	{
		//if there are patient segments we grab claims from that since 
		//the subscriber should not have any claims associated with it.
		if (subscriber.G_TS837_2000C != null)  
		{
			foreach(var patient in subscriber.G_TS837_2000C)
			{
				//parse out demographic information
				foreach (var claim in patient.G_TS837_2300_1)
				{
					//parse out claim information
					foreach (var line in claim.G_TS837_2400_1)
					{
						//Parse out line information
         				records.Add(record);
					}
				}
			}
		}
		else
		{
			//parse out demographic information.. Same exact logic as above but a different type
			foreach (var claim in subscriber.G_TS837_2300)
			{
				//parse out claim information.. Same exact logic as above but a different type
				foreach (var line in claim.G_TS837_2400)
				{
					//Parse out line information.. Same exact logic as but a different type
					records.Add(record);
				}
			}
		}
	}
	return records;
}

.
etc
.
etc
.

```

I wished to use the new XSD/Classes for validation and the old 5010 837 superset (non-hipaa specific) to do all of my parsing.  I could not see a way to accomplish this with the way Rules namespaces are setup.  It's nice that we can choose an assembly and namespace prefix but with the message version as part of the namespace it is not possible to use the same class for the different spec versions..

To that end I changed the way my Rules namespaces are defined so that all X12 definitions fall under the namespace "EdiFabric.Rules.X12" and the class name is the message type and specific version. (e.g. M_837_005010X223A2).  

I changed the MessageLexer .ToType like so

```
        private static Type ToType(Formats format, string version, string tag, string rulesAssemblyName, string rulesNamespacePrefix)
        {
            var typeName = "M_" + tag + "_" + version;
            var rulesAssembly = rulesAssemblyName ?? RulesAssembly;
            var namespacePrefix = rulesNamespacePrefix ?? "EdiFabric.Rules";
            var typeFullName = namespacePrefix.TrimEnd('.') + "." + format + "." + typeName;
            var systemType = Type.GetType(typeFullName + ", " + rulesAssembly);

            if (systemType == null)
                throw new ParserException(
                    string.Format(
                        "Type '{0}' was not found in assembly '{1}'.",
                        typeFullName, rulesAssemblyName));

            return systemType;
        }

```

This way I can have one namespace EdiFabric.ParsingRules use the old 5010 M_837 superset class as the base class for every specification and work the way I used to when parsing. And use another namespace EdiFabric.ValidationRules to use the new hipaa specific xsd/classes for validating.

```
    public class M_837_005010X222 : M_837 {  }
    public class M_837_005010X222A1 : M_837 {  }
    public class M_837_005010X223A2 : M_837 {  }
   //etc
```

Just thought I would share my experience, 
not sure if it is really an issue for anyone else
Tim M.

**Comment by tmeindle** [comment]
Disregard this..  I was over thinking..  The same effect can be accomplished using the namespaces

**Comment by DonZoeggerle** [comment]
You can have a custom namespace to support multiple versions of the same transaction set in the same project, e.g. the first part of the namespace is configurable. I understand you've figured that out yourself.
