### ISSUE TITLE
3060 855 POA producing empty fields and default enum fields

### ISSUE THREAD

**Issue by jrambharose** [DonZoeggerle/ediFabric#37]
Edifabric version 6.7.7
EDI version 3060
Transaction set 855 POA

We are having issues generating a proper 855 POA from an 855 EDI object. After assigning member variables proper values we seem to be producing blanks within the segment for variables not set or omitted. Qualifier variables tied to enums are being defaulted to the first enum value, in this case A1, even when the corresponding 'Specified' variables is false (defaults to false). Please advise. 

Code
```
//PO1
gPO1.S_PO1.D_350_1 = item.AssignedIdentification.ToString(); 
gPO1.S_PO1.D_330_2 = item.QuantityOrdered.ToString(); 
gPO1.S_PO1.D_355_3 = EdiFabric.Definitions.X12_003060_855.X12_ID_355.EA; 
gPO1.S_PO1.D_235_6 = EdiFabric.Definitions.X12_003060_855.X12_ID_235.VA; 
gPO1.S_PO1.D_234_7 = item.Isbn; 
gPO1.S_PO1.D_235_8 = EdiFabric.Definitions.X12_003060_855.X12_ID_235.EN; 
gPO1.S_PO1.D_234_9 = Util.Isbn.Convert(item.Isbn, Util.IsbnType.Ean13_978);
                
//ACK
gACK1.S_ACK.D_668_1 = (item.ItemStatus == ItemStatus.AcceptedAndReleased ? EdiFabric.Definitions.X12_003060_855.X12_ID_668.AR : EdiFabric.Definitions.X12_003060_855.X12_ID_668.IR); 
gACK1.S_ACK.D_380_2 = item.QuantityOrdered.ToString();
gACK1.S_ACK.D_355_3 = EdiFabric.Definitions.X12_003060_855.X12_ID_355.EA; 
```

Result
```
PO1*1*10*EA**03*VA*1628940409*EN*9781628940404*A1**A1**A1**A1**A1**A1**A1**A1~
ACK*IR*10*EA*001***A1**A1**A1**A1**A1**A1**A1**A1**A1**A1**94~
```

**Comment by DonZoeggerle** [comment]
Hi,

Version 6.7.7 is not compatible with the old XSD and there are no enums anymore (apart from some mandatory fields in HIPAA). You should download the latest XSD packages from the download links you received from us. Alternatively send us an email with the transaction id's or the email that was used and we'll resend the links.
