### ISSUE TITLE
EDI 835 parsing error 4010 spec

### ISSUE THREAD

**Issue by Chief-One** [DonZoeggerle/ediFabric#38]
Hi guys,

I've recently purchased the 5010 HIPPA files and downloaded 4010 ones as well. Running into parsing issue with one of the 4010 file. Its throwing following error as if it can't parse out SVC tag correctly

"Requested value 'G0151' was not found."

File is attached with the ticket as well. Please provide some guidance on whats going on and how to fix.

[835-4010.txt](https://github.com/DonZoeggerle/ediFabric/files/569793/835-4010.txt)

**Comment by Chief-One** [comment]
Testing with the latest version 6.8

**Comment by DonZoeggerle** [comment]
Fixed in version 6.8.3
