### ISSUE TITLE
Reading a M_UTILTS file finds multiple S_ST records

### ISSUE THREAD

**Issue by JSCProjects** [DonZoeggerle/ediFabric#39]
When testing the version 6.8.2 I've noticed that it is impossible to load UTILTS files because of this:

ParseNodeExtensions.cs
internal static string MessageControlNumber(this IEnumerable<ParseNode> segments)
{
var msgHeader =
                segments.**SingleOrDefault**(
                    s =>
                        s.Name.StartsWith("S_UNH", StringComparison.Ordinal) ||
                        s.Name.StartsWith("S_ST", StringComparison.Ordinal));
.....

In a UTILTS file there will be a lot of S_STS records so upper code will always fail.
I've changed it to FirstOrDefault to test if this new version is giving us better performance.

**Comment by DonZoeggerle** [comment]
Fixed in version 6.8.3
