### ISSUE TITLE
It would be nice to have a pluggable way of supplying Xsds

### ISSUE THREAD

**Issue by jonreis** [DonZoeggerle/ediFabric#43]
From what I can tell users are forced to place their Xsds into an assembly file as an embedded resource. Perhaps they want to supply these Xsds on demand from the web, out of a database, or zip file. How about making this a "pluggable" option?

interface IXsdProvider
{
     Stream GetXsd(string name);
}

**Comment by DonZoeggerle** [comment]
I added an overload to Validate, which now can be called as 

Validate(Stream XSD)

When called as parameterless Validate() it still loads the XSD from the embedded resources.

**Comment by jonreis** [comment]
Don, thank you for the addition to the library.

Can you expose a function that would return the libraries expected name of the Xsd? Otherwise, I am not sure how I will know which Xsd to grab to supply to the Validate function.

For example:

      var ediItems = TestHelper.ParseX12(sample, Encoding.ASCII, "Edifact.Hipaa").ToList();
      var doc = ediItems.OfType<EdiFabric.Rules.X12005010X223A2837.M_837>().Single();
      var expectedName = GetSchemaName(doc.GetType().FullName);
      var xsd = LoadUpMyXsd(expectedName);
      var validationResult = doc.Validate(doc, xsd);


What I think I need is the GetSchemaName function. Unless of course I am missing something.

**Comment by jonreis** [comment]
Thanks DonZoeggerle for adding this
