### ISSUE TITLE
Feature Request - ValidationException Validate(object message, Stream xsd) should take a Func<Stream> not a stream

### ISSUE THREAD

**Issue by jonreis** [DonZoeggerle/ediFabric#46]
The xsd files can be very large and are cached within the EdiValidation classs. One should not have to load one up into a stream if the EdiValidation.Validate function does not require it.

I would recommend adding the following function:

ValidationException Validate(object message, Func<Stream> func)

That way, if the xsd has already been created and cached, the code within func can be skipped.

**Comment by jonreis** [comment]
I tried to create my own EdiValidation class to override functionality such as the hard-coded 

        if (EdiValidation.XsdCache.Count > 20)
          EdiValidation.XsdCache.Clear();

however; it utilizes to many internal and private classes/functions such as:

    internal MessageErrorContext(string name, string controlNumber)
    EdiValidation.MapErrorCode
    EdiValidation.BuildContext
    EdiValidation.ValidateStructure

I'm wondering what the best way is to provide some flexibility to this class? Perhaps it should not be a static class, rather it should be an abstract class with some entry points that the user can override to provide functionality such as where the Xsd is loaded from and some control over the caching.

If the user wants a static version of this they can always use a singleton. Just a thought.

**Comment by DonZoeggerle** [comment]
First part fixed in 7.0.6
For the moment the class remains static.
