### ISSUE TITLE
Multiple version support

### ISSUE THREAD

**Issue by mahyarmot** [DonZoeggerle/ediFabric#49]
Hi,
We have purchased multiple version of edifact and our application is going to support multiple versions of BAPLIE and COPARN files. 
The issue is, we have hard coded the source assembly name in the target *.config file and in the source assembly we have more than 1 M_BAPLIE file !! which causes EdiFabric Package choose the wrong version.
Is there any solution to implement our factory method instead of config file ??? 

![edifacts](https://cloud.githubusercontent.com/assets/6184301/21985073/bab33a46-dc01-11e6-8ebe-117302749763.png)

**Comment by DonZoeggerle** [comment]
Hi,

The way ediFabric resolves which class to instantiate is to derive it from the namespace. If you have 2 class baplie files then:
1. They are representing two different versions.
In this case, they can both be in the same assembly and based on the version of the received EDI message the correct class will be loaded:

EdiFabric.Rules.Edifact1911BAPLIE.M_BAPLIE
EdiFabric.Rules.EdifactD93ABAPLIE.M_BAPLIE

2. They are the same version, but a different declaration.
In this case, you should change the namespace part of one of the files like:

EdiFabric.Rules.Edifact.2ndVersion.D93ABAPLIE.M_BAPLIE
EdiFabric.Rules.EdifactD93ABAPLIE.M_BAPLIE

And call the reader with the version of the namespace:

var ediReader = EdifactReader.Create(Load(sample),
                    new ReaderSettings
                    {
                        RulesNamespacePrefix = "EdiFabric.Rules.Edifact.2ndVersion"
                    }
