### ISSUE TITLE
Cannot create UNT segment

### ISSUE THREAD

**Issue by ViktorBergman** [DonZoeggerle/ediFabric#5]
I have purchased the U96A package and need to specify the total number of segments in a message in the UNT segment, specifically field 0074. How can I get the segment count from the framework instead of counting it manually?

**Comment by DonZoeggerle** [comment]
You can set UNT numberr of segments like this:

```
var mInvoic = new M_INVOIC();
// ... build the message
                
var msg = new Message(mInvoic);
var segCount = msg.Item.Descendants().Count(d => d.Name.LocalName.StartsWith("S_"));
                
var nmn = new XmlNamespaceManager(new NameTable());
nmn.AddNamespace("p", "www.edifabric.com/edifact");

var untSegCount = msg.Item.XPathSelectElement("./p:S_UNT/p:D_0074_1", nmn);
untSegCount.SetValue(segCount);
```

**Comment by DonZoeggerle** [comment]
Closing this as it's been answered...

**Comment by ViktorBergman** [comment]
You answered my question a while ago so I'm satisfied.

Skickat från min Windows Phone
________________________________
