### ISSUE TITLE
Is .Net Core support in the works

### ISSUE THREAD

**Issue by jonwmccain** [DonZoeggerle/ediFabric#50]
Greetings,

I'm researching EDI Frameworks and am looking at edifabric and edi.net. Our target deployment model is on Azure within Service Fabric. Because of this I'm leaning towards those libraries that leverage .Net Core or its on the roadmap... 

Is the edifabric product team currently working on this or know of a fork for this?

I tried to change the .Net Framework reference in my cloned repository but it doesn't show up as an option even though I have the framework installed.

Thanks,

Jon

**Comment by DonZoeggerle** [comment]
Hi,

.Net Core is definitely on the roadmap, however, development will not go ahead until sometime in the Spring  I'm afraid.

Best,
Don

**Comment by jonwmccain** [comment]
Hi Don,

Thank you for the quick response.

I'm new to the EDI world... right now I've got the X12 parser from codeplex in a test app. I'm trying to select the best open source library for our project.

EDIFabric certainly has a slick site but what are the advantages of using it over x12parser or perhaps EDI.Net, the latter already supporting .Net Core (per their documentation at least)?

Thanks,

Jon

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by DonZoeggerle** [comment]
Hi Jon,

I can't comment on the other tools as I'm not familiar with them. 
ediFabric is a mature product and is running in production environments across multiple verticals, for more than 3 years now.
You can take a look at the [features section](http://edifabric.com/features.html) on our website for most of the things I'd like to see in an EDI product. Hope it's a good starting point when you evaluate the options.

Cheers,
Don

**Comment by jonwmccain** [comment]
Thanks Don. I appreciate it.

Jon W. McCain
RICS Software, Software Engineer
www.ricssoftware.com
@jmccain79<https://twitter.com/jwmccain79> | LinkedIn<https://www.linkedin.com/in/jon-mccain-8a11434?trk=nav_responsive_tab_profile>
