### ISSUE TITLE
Parsing error on 999 CTX segments

### ISSUE THREAD

**Issue by gregrcook** [DonZoeggerle/ediFabric#51]
EdiFabric,
I'm receiving a parsing error using the latest version of EdiFabric 7.2.1 with 999 files that have a CTX segment under IK3 or IK4. I'm using a copy of the 999 framework which was purchased in October and the code I am using to parse it follows the same flow as the AccessInterchangeSegments sample function available under the EdiToObject sdk.

I've attached two examples, one with and one without the CTX segment. The file with CTX segments returns a parsing error of "Requested value 'CLM01' was not found." The file without CTX segments returns an M_999 object as expected.

[example999.txt](https://github.com/DonZoeggerle/ediFabric/files/729854/example999.txt)
[example999_no_CTX.txt](https://github.com/DonZoeggerle/ediFabric/files/729853/example999_no_CTX.txt)

**Comment by DonZoeggerle** [comment]
Fixed in release 7.2.2
