### ISSUE TITLE
Unsupported Node Prefix: D

### ISSUE THREAD

**Issue by jdobbin-hsahealthplan** [DonZoeggerle/ediFabric#52]
I have an XSD that I purchased from EdiFabric that has elements with names like D_BGN01_TransactionSetPurposeCode that the latest code seems to choke on with an error message of "Unsupported node prefix: D". 

This error is coming from the ParseNodeExtensions.cs file that seems to have newly added some prefix validation logic into it.

Are the XSD's I purchased no longer valid in the latest update? Or is there something else I should be doing to address this?

Here's a simple test to parse an 834 that results in the list items having the "unsupported node prefix error":

```public class Translate_X12_834
{
    public static List<object> GetMessages(Stream ediStream)
    {
        var reader = X12Reader.Create(ediStream);
        var items = reader.ReadToEnd().ToList();

        return items;
    }
}
```

**Comment by jdobbin-hsahealthplan** [comment]
I've been debugging this issue further and here's the node.Path value I get when I stop at the exception being thrown in NeighboursWithExclusion():

M_834-1G_TS834_20006A_REF1G_REF_MemberSupplementalIdentifier1D_REF01_ReferenceIdentificationQualifier0

**Comment by jdobbin-hsahealthplan** [comment]
I ended up adding the following to the ParseNodeExtensions.NeighborsWithExclusions case statement and it seemed to do the trick, but I'm not sure it's the best approach:

```case Prefixes.D:
result.AddRange(node.Children);
result.Add(node.Parent);
return result;
```

**Comment by DonZoeggerle** [comment]
When did you purchase the package and which version of ediFabric Framework worked?

**Comment by jdobbin-hsahealthplan** [comment]
I purchased the package back in May 2016. 

Unfortunately it's never worked but I'm just barely getting back to trying again.

**Comment by DonZoeggerle** [comment]
You need to re-download the package as there was an update in August 2016. This was communicated, but you must have missed it.
In case you can't find the link, send us the package name and the email you used to purchase it and we'll resend it to you. Please send any further communication to office@edifabric.com as GitHub is only for issues.

You mentioned that only the latest code chokes on certain elements, that's why I assumed that the previous code didn't.

**Comment by jdobbin-hsahealthplan** [comment]
Thanks for your help.
