### ISSUE TITLE
Is there any way to convert .Net object back to EDI message

### ISSUE THREAD

**Issue by bikashsharmabks** [DonZoeggerle/ediFabric#55]
We have use case where we need to change certain segment value in .NET object library

@DonZoeggerle is there any way in the library to convert .net object back to EDI message. Any specific unit test case that covers this.

Thanks
Keep the great work!!!!

**Comment by DonZoeggerle** [comment]
Yes you can create EDI messages. We are working on the documentation for this, but you can browse all unit tests for creating and look at samples [here](https://github.com/DonZoeggerle/ediFabric.Sdk.ObjectToEdi)

**Comment by DonZoeggerle** [comment]
I also added documentation to the wiki. closing the issue.
