### ISSUE TITLE
How to exclude unnecessary codes in 278 format?

### ISSUE THREAD

**Issue by ianmakecode** [DonZoeggerle/ediFabric#56]
using the default format for outputting X12 data:
```
var ediInterchange = new X12Interchange(interchangeHeader);
            ediInterchange.AddItem(ediGroup);

            IEnumerable<string> ediSegments = ediInterchange.GenerateEdi();

            // your EDI message without postfix
            string edi = ediSegments.Aggregate("",
                            (current, segment) => current + segment);

            // your EDI message with new line as postfix
            string ediPostfix = ediSegments.Aggregate("",
                            (current, segment) =>
                                current + segment + Environment.NewLine);
```
Only problem with this is that it seems that even items marked as "unspecified" -- which is achieved by setting the (e.g.) 2000A.UMO.SomethingSomethingCodeSpecified = false -- are still popping out in the final edi text result. As I debug I see that every single one of these CodeSpecified's in my M_278 object (which I do not want hanging around) are set to false, but their code values still seem arrive in the result. Am I missing something? It does not seem like the .GenerateEdi() does any checking for stuff like this; is it a Schema thing? What am I doing wrong? 

Thanks, 
Ian

**Comment by DonZoeggerle** [comment]
We do not support Specified on schemas any more since version 6.7.3. You can update your Spec packages from the download links or send us an email to office@edifabric.com to request for an update. Please specify which packages you need and the email you used to purchase them.

Regards,
Don

**Comment by ianmakecode** [comment]
So, how is this handled in formats after 6.7.3?  Are there no more enums?  Thank you very much for your quick response, Don.  5/5

**Comment by DonZoeggerle** [comment]
For Hipaa (part of which is 278) the enums are reduced to only the first two elements of each segment and only if they are mandatory. So in practice you won't need to exclude them as they are mandatory according to the standard. The non compulsory ones were changed to strings.

Don

**Comment by ianmakecode** [comment]
Alright!  Thanks for the intel.

**Comment by DonZoeggerle** [comment]
Closing the issue.

**Comment by ianmakecode** [comment]
Are you sure it is version 6.7.3?  Where can I view version history with respect to your version numbers, and not github commits?

Thanks,
Ian
