### ISSUE TITLE
ediFabric support for .net core

### ISSUE THREAD

**Issue by bikashsharmabks** [DonZoeggerle/ediFabric#57]
We are building web api using .net core which shall use edi fabric for edi transformation as a micro service

But when I try to add edifabric.framework using nuget it says edifabric is not compatible with .net core.

 Package ediFabric.Framework 7.3.1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package ediFabric.Framework 7.3.1 supports: net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETStandard,Version=v1.6.
Done: 1.

So does ediFabric supports .net core or in near future?

![image](https://cloud.githubusercontent.com/assets/4053186/23331735/ebf61178-fb91-11e6-8315-807788f4034d.png)

Thanks

**Comment by DonZoeggerle** [comment]
Hi,

We will be supporting .NET Core, however the validation relies on XmlSchema which has not yet been ported to .NET Core 1.1. According to Microsoft this will be supported with the Core 2.0 release (due in May 2017) and once available we'll incorporate it. 

Best,
Kamen

**Comment by DonZoeggerle** [comment]
The latest version 8.0 can be referenced from any .NET Core project. We'll be working on a full .NET Core implementation very soon.
Closing this one...
