### ISSUE TITLE
ParsingException when reading EDIFACT interchange with interchange control reference like "UNA1234" or "UNB1234"

### ISSUE THREAD

**Issue by jkagerst** [DonZoeggerle/ediFabric#59]
When parsing an EDIFACT interchange with an interchange control reference like "UNA1234" or "UNB1234", EdifactReader.ReadToEnd() returns a ParsingException ("Unprocessed segments before the end of file.") as final item.

Example content:

`UNA:+.? 'UNB+UNOA:3+1:ZZZ+2:ZZZ+20170324:1419+UNA1234'UNH+1+INVOIC:D:00A:UN:EAN010'BGM+220+1+9'UNT+3+1'UNZ+1+UNA1234'`

As soon as more than four characters follow after "UNA" or "UNB" (e. g. "UNB12345"), the exception doesn't occur.

I attached a Unit Test class for the Test Project which demonstrates the problem:

[TestInterchangeReference.cs.txt](https://github.com/DonZoeggerle/ediFabric/files/867966/TestInterchangeReference.cs.txt)

**Comment by DonZoeggerle** [comment]
I've just ran the sample test and it was fine, using version 7.3.0. Which version of the framework are you testing with ?

**Comment by DonZoeggerle** [comment]
Closing the issue.
