### ISSUE TITLE
InvalidOperationException during deserializing message

### ISSUE THREAD

**Issue by AnoopChauhan** [DonZoeggerle/ediFabric#6]
Hi I' Anoop Chauhan from India. I've purchased D95B, 

////////////////////////////////////
var interchange = Interchange.LoadFrom(File.OpenRead(@"testd95b2.edi"));
var msg = interchange.Groups[0].Messages[0];
var typedmsg = msg.DeserializeItem<'M_BAPLIE'>();

this throws System.InvalidOperationException, which is because of validation errors ( some wrong data elements value in Edifact file), but I want them to be parsed at any cost, how to do that?

How can I turn off enum validation in framework? requires some code changes?

**Comment by DonZoeggerle** [comment]
Hi,
the only way to go around this is to edit the class file and to change the enum fileds\properties to be of string type. Another way is to implement custom deserialization to skip over these, but that would be cumbersome.
That's the purpose of the class files anyway - they can be extended\amended to fit into whatever you need.
Don

**Comment by AnoopChauhan** [comment]
Hi Don, 
 
I've done this,it works
in BAPLIE.cs I replaced enum fields like

private EDIFACT_ID_1001 d_1001_1Field
to
private string d_1001_1Field;

so its public properties.
thank you
