### ISSUE TITLE
Movins file 95B directory not work

### ISSUE THREAD

**Issue by aseif83** [DonZoeggerle/ediFabric#60]
I purchased D.95B Directory files to support Baplie and Movins files for our customer.
when i try to parse any movin file,edifabric parser through parsingException "Segment was not in the correct position according to the rules class.

Movins file attached

[Movins Loading.txt](https://github.com/DonZoeggerle/ediFabric/files/875083/Movins.Loading.txt)

"

**Comment by DonZoeggerle** [comment]
This is data issue and not a bug\cr so please don't publish these in GitHub.
Unless you are on a paid support plan we don't investigate data issues - your options are:
1. Try to debug it\enable logging and match the segments against the rules class\XSD.
2. Post to StackOverflow
