### ISSUE TITLE
Using the Ackman to generate 999 always return HasErrors = true

### ISSUE THREAD

**Issue by bikashPeople10** [DonZoeggerle/ediFabric#61]
I am Generating a 999 ack for X12 835 message using Ackman Plugin but for any message it generates ack with rejects having below segment always 

```
IK5*R*5~
AK9*R*1*1*0~
```

EDI X12 message seems to be fine with no errors but still I get HasErrors = true for MessageHandler event. And when I try to look for ErrorCode it seems to have unknown error code in it

![ack_999](https://cloud.githubusercontent.com/assets/25300235/25082461/9e648c28-236e-11e7-85f6-6620118f1534.png)

![debug messagehandler](https://cloud.githubusercontent.com/assets/25300235/25082533/173d4766-236f-11e7-934a-af5212e51f98.png)

let me know if I am doing anything wrong.

**Comment by DonZoeggerle** [comment]
Could you please send me your sample project to office@edifabric.com to investigate ?

**Comment by DonZoeggerle** [comment]
Resolved
