### ISSUE TITLE
Generated X12005010X217278.M_278 cannot be read

### ISSUE THREAD

**Issue by ianmakecode** [DonZoeggerle/ediFabric#62]
Hello,
We've generated a series of 278 files using EdiFabric's X12 generation features, however we'd like to merge all the M_278s into a single group segment in a single isa, in a single file, but our generated 278s are not being recognized by the X12Reader.  ISA and GS are discovered just fine.  We're using the Assembly.Load / RulesNamespace / Encoding.ASCII route to create the X12Reader, along with OfType<M_278>. 

My question is, is there any reason that a segment generated by EdiFabric would then be perceived by EdiFabric as invalid input?  We're doing nothing to edit these output 278's, they're essentially going right back into EdiFabric, using the exact same Assembly/Class to parse as they were built.

Thanks,
Ian Ray

**Comment by DonZoeggerle** [comment]
Hi,
The rules files can be amended according to the [rules guide](http://edifabric.com/files/rulesdiy.pdf).
To make a class discover able the last portion of the namespace must be preserved, e.g. EdifactD00AINVOIC.

Segments generated by ediFabric are just strings. They can surely be invalid if the properties were populated with incorrect data.

This isn't a bug\cr so I'm closing the issue. Please follow up on office@edifabric.com if any other questions.
