### ISSUE TITLE
Problem with properties markes with attribute XmlIgnoreAttribute

### ISSUE THREAD

**Issue by keret** [DonZoeggerle/ediFabric#63]
In previous versions (6.7.3) properties marked with XmlIgnoreAttribute were fitered out in Sort extension method in ExtensionsPropertyInfo class.
Maybe it's not ideal place to filter out list elements but in new version (7.3.1) while parsing all properties are taken into consideration. It result in error while processing class generated with Xsd2Code or Xsd.exe tools (nullable properties have additional properties with "Specified" suffix and those properties are marked with XmlIgnoreAttribute).
Modifying Sort method in PropertyInfoExtensions class to:

internal static IEnumerable<PropertyInfo> Sort(this PropertyInfo[] propertyInfos)
        {
            return propertyInfos.Where(p => p.GetCustomAttribute(typeof(XmlIgnoreAttribute)) == null).
            OrderBy(
                p =>
                    p.GetCustomAttributes(typeof(XmlElementAttribute), false)
                        .Cast<XmlElementAttribute>()
                        .Select(a => a.Order)
                        .FirstOrDefault());           
        }

does the trick.

**Comment by DonZoeggerle** [comment]
Properties annotated with XmlIgnoreAttribute are not supported anymore, please update your schemas.
Not an issue as it is using unsupported schemas.

**Comment by DonZoeggerle** [comment]
Properties annotated with XmlIgnoreAttribute are not supported anymore, please update your schemas.
Not an issue as it is using unsupported schemas.
