### ISSUE TITLE
Unable to Read X12 Files With Repeating 2000A or 2000B Loops

### ISSUE THREAD

**Issue by nratcliff** [DonZoeggerle/ediFabric#66]
A valid 5010 837P file is attached.    [Repeating2000Bs.txt](https://github.com/DonZoeggerle/ediFabric/files/1082802/Repeating2000Bs.txt)

When this file is read with the X12 reader, the transaction set is not parsed and this error is available: "Index was out of range. Must be non-negative and less than the size of the collection."

The issue occurs in the Analyze() method of Framework\Model\TransactionSet.cs

                    currSeg =
                        this.Descendants<Segment>()
                            .FirstOrDefault(
                                d => d.EdiName == "HL" && d.Children.ElementAt(1).Value == segment.SecondValue);

When HL*3*1*22*0 is hit in the file, there are no children for the repeated HL.

![codeanderror](https://user-images.githubusercontent.com/1576607/27256839-13039d8c-5388-11e7-85c9-9891e0772f3d.png)

**Comment by DonZoeggerle** [comment]
Fixed in release 8.0.4
