### ISSUE TITLE
Interchange.LoadFrom() method returns exception value not found

### ISSUE THREAD

**Issue by tarekselem** [DonZoeggerle/ediFabric#7]
While loading EDI file  returns the following exception :
An unhandled exception of type 'System.ArgumentNullException' occurred in EdiFabric.Framework.dll

Additional information: Value cannot be null.

**Comment by DonZoeggerle** [comment]
Can you give more details ? Perhaps the stream is null ?

**Comment by DonZoeggerle** [comment]
Closing as not enough information\can't reproduce.
